### ISSUE TITLE
Dockerhub link

### ISSUE THREAD

**Issue by guruvan** [GroestlCoin/docker-groestlcoind-base#1]
"Note: Automated Builds currently require read and write access since Docker Hub needs to setup a GitHub service hook. We have no choice here, this is how GitHub manages permissions, sorry! We do guarantee nothing else will be touched in your account."

@gruve-p I think because "service hook" (as opposed to "webhook") connection to github for automated dockerhub builds requires someone w r/w access to the _Organization_ 

Probably the best thing to do here, is setup  a Role Account (bot) and share the access to the account for the moment to get all this setup. Then we can use the same account for connections to travis-ci for these and other projects.

**Comment by guruvan** [comment]
http://docs.docker.com/docker-hub/builds/

**Comment by gruve-p** [comment]
Role account GRSPullTester created
